-- Socle Omega : SOUCHE LOCALE pour valider les migrations A4 hors recette. Ne s'exécute jamais ailleurs.
create schema if not exists private; create schema if not exists extensions; create schema if not exists auth;
do $$ begin
  if not exists (select 1 from pg_roles where rolname='anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname='service_role') then create role service_role nologin bypassrls; end if;
end $$;
grant usage on schema public, private, extensions, auth to anon, authenticated, service_role;
create or replace function extensions.digest(bytea, text) returns bytea language sql immutable as $$ select public.digest($1, $2) $$;
create or replace function auth.uid() returns uuid language sql stable as $$
  select (nullif(current_setting('request.jwt.claims', true), '')::json->>'sub')::uuid $$;
create table auth.users (id uuid primary key, email text, instance_id uuid, aud text, role text, encrypted_password text, created_at timestamptz, updated_at timestamptz);

-- ── Tables du socle ──
create table public.clients (id uuid primary key default gen_random_uuid(), nom text not null, statut text default 'prospect', profil text default 'generique', siren text);
create table public.entites (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade, nom text not null, type text default 'societe', principale boolean default false, fuseau text default 'Europe/Paris', siren text, territoire text);
create unique index entites_une_principale_idx on public.entites (client_id) where principale;
create function private.stub_entite_principale() returns trigger language plpgsql as $$ begin insert into public.entites (client_id, nom, principale) values (new.id, new.nom, true); return new; end $$;
create trigger clients_entite_principale after insert on public.clients for each row execute function private.stub_entite_principale();
create table public.comptes (id uuid primary key default gen_random_uuid(), user_id uuid not null, client_id uuid not null references public.clients(id) on delete cascade, role text default 'gerant', perimetre_total boolean default true, unique (user_id, client_id));
create table public.comptes_entites (user_id uuid, client_id uuid, entite_id uuid);
create table public.equipes (id uuid primary key default gen_random_uuid(), client_id uuid not null, nom text not null);
create table public.equipes_membres (equipe_id uuid, user_id uuid);
create table public.pieces (id uuid primary key default gen_random_uuid(), client_id uuid not null, module text not null, source text not null check (source in ('depot','courriel','connecteur','export','api')), nom_fichier text not null, mime text not null, octets bigint not null, sha256 text not null, chemin text not null, objet_type text, objet_id text, statut text default 'recue');
create table public.pieces_valeurs (id uuid primary key default gen_random_uuid(), client_id uuid, piece_id uuid, champ text, valeur jsonb, texte text, source text, confiance numeric, verifiee boolean, controle text);
create table public.journal_opposable (id bigserial primary key, client_id uuid not null, entite_id uuid, survenu_le timestamptz not null default now(), acteur_type text not null default 'systeme', acteur_id uuid, acteur_libelle text, action text not null, objet_type text not null, objet_id text not null, donnees jsonb not null default '{}', hash_precedent bytea, hash bytea);
create table public.alertes (id uuid primary key default gen_random_uuid(), client_id uuid, interne boolean not null default false, niveau text not null check (niveau in ('info','attention','critique')), source text not null, titre text not null check (char_length(titre) between 1 and 200), detail jsonb default '{}', cle_regroupement text, destinataire uuid, cree_le timestamptz default now(), close_le timestamptz, acquittee_le timestamptz);
create unique index alertes_ouvertes on public.alertes (coalesce(client_id, '00000000-0000-0000-0000-000000000000'::uuid), cle_regroupement) where close_le is null;
create table public.regles_validation (id uuid primary key default gen_random_uuid(), client_id uuid not null, entite_id uuid, module text not null, montant_min numeric not null default 0 check (montant_min >= 0), montant_max numeric check (montant_max is null or montant_max > montant_min), approbations_requises smallint not null default 1 check (approbations_requises between 1 and 3), roles_autorises text[] not null default array['gerant','admin','valideur'] check (roles_autorises <@ array['gerant','admin','valideur'] and cardinality(roles_autorises) >= 1), actif boolean not null default true, cree_le timestamptz default now(), type_action text check (type_action is null or char_length(type_action) between 1 and 80), equipe_id uuid);
create table public.demandes_validation (id uuid primary key default gen_random_uuid(), client_id uuid not null, entite_id uuid, module text not null check (module ~ '^[a-z][a-z_]{1,29}$'), type_action text not null check (char_length(type_action) between 1 and 80), objet_type text not null, objet_id text not null, resume text not null check (char_length(resume) between 1 and 500), montant numeric check (montant is null or montant >= 0), devise char(3) default 'EUR', payload jsonb not null default '{}', demandeur_type text, demandeur_id uuid, statut text not null default 'en_attente' check (statut in ('en_attente','approuvee','rejetee','annulee','expiree','executee','echec_execution')), approbations_requises smallint, roles_autorises text[], regle_id uuid, echeance timestamptz, cle_idempotence text not null, cree_le timestamptz default now(), decide_le timestamptz, execute_le timestamptz, motif_echec text, equipe_id uuid, politique_id uuid, unique (client_id, cle_idempotence));
create table public.approbations (id uuid primary key default gen_random_uuid(), demande_id uuid not null references public.demandes_validation(id), client_id uuid, user_id uuid, au_nom_de uuid, delegation_id uuid, decision text not null check (decision in ('approuve','rejete')), commentaire text check (commentaire is null or char_length(commentaire) <= 2000), decide_le timestamptz default now(), cree_le timestamptz default now(), unique (demande_id, user_id));
create table public.delegations (id uuid primary key default gen_random_uuid(), client_id uuid not null, delegant uuid not null, delegataire uuid not null, entite_id uuid, module text, debut timestamptz not null, fin timestamptz not null, motif text, cree_par uuid, cree_le timestamptz default now(), revoquee_le timestamptz);
create table public.travaux (id bigserial primary key, client_id uuid, module text, genre text, charge jsonb default '{}', cle text, priorite smallint default 0, statut text default 'a_faire', issue jsonb, erreur text, cree_le timestamptz default now());
create table public.battements (client_id uuid, module text, dernier_le timestamptz, primary key (client_id, module));
create table public.indicateurs (code text not null check (code ~ '^[a-z][a-z_]{1,29}\.[a-z][a-z0-9_.]{1,79}$'), version smallint not null check (version between 1 and 999), libelle text not null check (char_length(libelle) between 3 and 120), definition text not null check (char_length(definition) between 10 and 2000), formule text not null check (char_length(formule) between 3 and 500), unite text not null check (unite in ('%','nombre','euros','jours','heures','minutes')), sens text not null check (sens in ('hausse','baisse')), agregation text not null check (agregation in ('moyenne','somme','dernier')), decimales smallint not null default 0 check (decimales between 0 and 3), droit_lecture text check (droit_lecture ~ '^[a-z][a-z0-9_.]{1,59}$'), droit_detail text check (droit_detail ~ '^[a-z][a-z0-9_.]{1,59}$'), source text check (source is null or char_length(source) <= 500), en_service boolean not null default true, primary key (code, version), check (not (unite = '%' and agregation = 'somme')));
create table public.mesures (id uuid primary key default gen_random_uuid(), client_id uuid not null, indicateur text not null, version smallint not null, mode text not null check (mode in ('a_blanc','reel')), periode_type text not null, debut date not null, fin date not null, valeur numeric, numerateur numeric, base numeric, entite_id uuid, objet_type text, objet_id text, objet_libelle text, unique nulls not distinct (client_id, indicateur, version, mode, periode_type, debut, fin, entite_id, objet_type, objet_id));
create table private.tables_locataires (nom text primary key, ordre_effacement smallint not null default 100, note text);
create table private.tables_objets (nom text primary key, objet_type text not null, colonne text not null, ordre_effacement smallint not null default 100);
create table private.abonnements (evenement text, module text, genre text, unique (evenement, module, genre));
insert into private.abonnements values ('demande.decidee.filed', 'filed', 'filed.decision');

-- ── Tables FILED ──
create table public.filed_reglages (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade, entite_id uuid, actif boolean not null default true, cree_le timestamptz default now(), maj_le timestamptz default now(), tolerance_totaux numeric default 0.05, doublon_fenetre_jours smallint default 3, seuil_mentions_ht numeric default 150, ecart_prix_pct numeric default 2, ecart_prix_montant numeric default 0.05, ecart_quantite_pct numeric default 0, commande_exigee boolean default false, commande_exigee_des_ht numeric default 0, reception_exigee boolean default false, unique nulls not distinct (client_id, entite_id));
create table public.filed_compteurs (client_id uuid, nature text, annee smallint, dernier int default 0, primary key (client_id, nature, annee));
create table public.filed_documents (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade, entite_id uuid not null, annee_reception smallint, numero_reception int, reference text generated always as ('R' || annee_reception || '-' || lpad(numero_reception::text, 6, '0')) stored, piece_id uuid not null, source text, expediteur text, depose_par uuid, nom_fichier text not null, sha256 text, recu_le timestamptz not null default now(), etat text default 'a_traiter', nature text, nature_source text check (nature_source is null or nature_source in ('lecteur','humain')), constraint filed_documents_nature_sourcee check ((nature is null) = (nature_source is null)), doublon_de uuid, motif text, lu_le timestamptz, traite_le timestamptz);
create table public.filed_historique (id bigserial primary key, client_id uuid not null, document_id uuid, objet_type text not null check (objet_type ~ '^filed_[a-z_]{1,33}$'), objet_id text, etape text not null check (etape ~ '^[a-z][a-z0-9_.]{1,59}$'), message text not null check (char_length(message) between 1 and 500), detail jsonb default '{}', acteur_type text check (acteur_type in ('utilisateur','operateur','systeme')), acteur_id uuid, acteur_libelle text, survenu_le timestamptz not null default now());
create table public.filed_fournisseurs (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade, code text, nom text not null, nom_normalise text, siren text, siret text, tva text, id_etranger text, pays text, statut text not null default 'actif' check (statut in ('a_confirmer','actif','bloque','refuse')), source text not null check (source in ('facture','piece','saisie','import')), document_origine uuid, regime_tva text default 'normal', confirme_le timestamptz, confirme_par uuid, motif text, maj_le timestamptz default now(), constraint filed_fournisseurs_siren_key unique (client_id, siren));
create table public.filed_fournisseurs_ibans (id uuid primary key default gen_random_uuid(), client_id uuid, fournisseur_id uuid references public.filed_fournisseurs(id), iban text, iban_masque text, empreinte text, statut text, source text, document_id uuid, propose_par uuid, propose_le timestamptz, decide_le timestamptz, decide_par uuid, motif text);
create table public.filed_factures (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade, entite_id uuid, document_id uuid not null references public.filed_documents(id) on delete cascade unique, nature text not null default 'facture' check (nature in ('facture','avoir')), version int not null default 1 check (version >= 1), numero text, numero_normalise text, date_emission date, date_reception date not null default current_date, echeance_lue date, devise text not null default 'EUR', montant_ht numeric, montant_tva numeric, montant_ttc numeric, net_a_payer numeric, montant_prepaye numeric, montants_calcules text[] default '{}', type_code text, cadre_facturation text, regime_tva text, fournisseur_id uuid references public.filed_fournisseurs(id), fournisseur_identification text, fournisseur_force boolean default false, fournisseur_lu jsonb default '{}', acheteur_lu jsonb default '{}', iban text, refs jsonb default '{}', mentions jsonb default '{}', champs_douteux jsonb default '[]', empreinte_donnees text, statut text not null default 'a_completer' check (statut in ('a_completer','bloquee','a_valider','ecartee')), doublon_de uuid, anomalies text[] default '{}', nb_bloquants int default 0, nb_attention int default 0, controle_le timestamptz, cree_le timestamptz default now(), maj_le timestamptz default now(), commande_id uuid, commande_force boolean, avoir_de uuid, unique (client_id, id));
create table public.filed_factures_lignes (id uuid primary key default gen_random_uuid(), client_id uuid, facture_id uuid references public.filed_factures(id) on delete cascade, document_id uuid, rang int, numero text, reference_vendeur text, reference_acheteur text, gtin text, designation text, quantite numeric, unite text, prix_unitaire numeric, prix_brut numeric, remise numeric, montant_ht numeric, taux_tva numeric, categorie_tva text, commande_ligne text, source text not null check (source in ('xml','regle','ia','humain','tableur')));
create table public.filed_factures_tva (id uuid primary key default gen_random_uuid(), client_id uuid, facture_id uuid references public.filed_factures(id) on delete cascade, document_id uuid, categorie text, taux numeric, base numeric, montant numeric, motif text, source text);
create table public.filed_controles (id uuid primary key default gen_random_uuid(), client_id uuid, facture_id uuid references public.filed_factures(id) on delete cascade, document_id uuid, version int, code text not null check (code ~ '^[a-z][a-z_]{1,30}\.[a-z][a-z_]{1,40}$'), famille text generated always as (split_part(code, '.', 1)) stored, gravite text check (gravite in ('bloquant','attention','info')), resultat text check (resultat in ('ok','anomalie','levee')), message text check (char_length(message) between 1 and 500), motif_officiel text, preuve jsonb default '{}', cle text not null default '', levee_id uuid, cree_le timestamptz default now(), unique (facture_id, code, cle));
create table public.filed_levees (id uuid primary key default gen_random_uuid(), client_id uuid, facture_id uuid, document_id uuid, code text, cle text, motif text, leve_par uuid, leve_le timestamptz default now(), unique (facture_id, code, cle));
create table public.filed_commandes (id uuid primary key default gen_random_uuid(), client_id uuid, entite_id uuid, document_id uuid, fournisseur_id uuid, numero text, numero_normalise text not null, source text not null check (source in ('piece','import','saisie')), statut text default 'ouverte', montant_ht numeric);
create table public.filed_commandes_lignes (id uuid primary key default gen_random_uuid(), client_id uuid, commande_id uuid references public.filed_commandes(id), rang int, designation text, reference text, quantite numeric, prix_unitaire numeric, montant_ht numeric, source text not null check (source in ('xml','regle','ia','humain','tableur','import','saisie')));
create table public.filed_receptions (id uuid primary key default gen_random_uuid(), client_id uuid, document_id uuid, commande_id uuid, statut text default 'enregistree');
create table public.filed_receptions_lignes (id uuid primary key default gen_random_uuid(), reception_id uuid references public.filed_receptions(id), commande_ligne_id uuid, quantite numeric);
create table public.filed_rapprochements (id uuid primary key default gen_random_uuid(), client_id uuid, facture_id uuid unique references public.filed_factures(id) on delete cascade, document_id uuid, version int, commande_id uuid, commande_source text, reception_id uuid, mode text, nb_lignes int, nb_appariees int, nb_sans_commande int, ecart_prix numeric, ecart_quantite numeric, deja_facture numeric, non_recu numeric, ecart_montant numeric, preuve jsonb);
create table public.filed_rapprochements_lignes (id uuid primary key default gen_random_uuid(), client_id uuid, facture_id uuid references public.filed_factures(id) on delete cascade, document_id uuid, facture_ligne_id uuid, commande_ligne_id uuid, methode text, sens smallint, quantite numeric, prix_facture numeric, prix_commande numeric, ecart_prix_unitaire numeric, ecart_prix numeric, quantite_commandee numeric, deja_facture numeric, quantite_recue numeric, ecart_quantite numeric, ecart_quantite_montant numeric, non_recu numeric, non_recu_montant numeric, resultat text);
create table public.filed_appariements (id uuid primary key default gen_random_uuid(), client_id uuid, facture_id uuid, document_id uuid, facture_ligne_id uuid, commande_ligne_id uuid, motif text);
create table public.filed_motifs_refus (code text primary key, libelle text, description text);
insert into public.filed_motifs_refus (code, libelle) values ('EMMET_INC','Émetteur inconnu'),('NON_CONFORME','Mention légale manquante'),('CALCUL_ERR','Erreur de calcul'),('DOUBLON','Doublon'),('CREANCIER_ERR','Créancier'),('COORD_BANC_ERR','Coordonnées bancaires'),('DEST_ERR','Destinataire'),('TX_TVA_ERR','Taux de TVA'),('MODPAI_ERR','Modalités de paiement'),('QTE_ERR','Quantité'),('PU_ERR','Prix unitaire'),('LIVR_INCOMP','Livraison incomplète'),('MONTANT_ERR','Montant'),('MONTANTTOTAL_ERR','Montant total');
create table public.filed_taux_tva (regime text, taux numeric, libelle text, article text, en_vigueur_du date, en_vigueur_au date);
insert into public.filed_taux_tva (regime, taux, libelle) values ('metropole', 20, 'normal'), ('metropole', 10, 'intermédiaire'), ('metropole', 5.5, 'réduit'), ('metropole', 2.1, 'particulier');
insert into private.tables_locataires (nom, ordre_effacement, note) values ('filed_factures', 6, 'F2'), ('filed_documents', 8, 'F1'), ('filed_fournisseurs', 25, 'F2');
insert into private.tables_objets (nom, objet_type, colonne, ordre_effacement) values ('filed_documents', 'filed_document', 'id', 90), ('filed_factures', 'filed_document', 'document_id', 20);
alter table public.filed_documents enable row level security; alter table public.filed_factures enable row level security;
grant select on all tables in schema public to authenticated, service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
