/* La file de validation d'exemple — voir exemples/socle.ts (05/10/2026).
   Les formes sont celles de components/espace/types.ts, donc celles des
   tables demandes_validation, approbations, delegations, regles_validation. */

import type { Approbation, Delegation, Demande, Regle } from "../types";
import { AGENCE, CLAIRE, EXEMPLE_CLIENT_ID, EXEMPLE_MOI, MARC, SIEGE, SOFIA, YANIS, dans, ilYa } from "./socle";

const C = EXEMPLE_CLIENT_ID;
const id = (n: number) => `00000000-0000-4000-8000-0000000000d${n.toString(16)}`;

export const DEMANDES_EXEMPLE: Demande[] = [
  {
    id: id(1),
    client_id: C,
    entite_id: SIEGE,
    module: "cashd",
    type_action: "virement_fournisseur",
    objet_type: "filed_facture",
    objet_id: "R2026-000009",
    resume: "Virement à Métallerie Roux — facture MR-2026-0412, 12 480,00 €",
    montant: 12480,
    devise: "EUR",
    payload: {
      beneficiaire: "Métallerie Roux SARL",
      iban: "FR76 3000 4000 0512 3456 7890 143",
      reference: "MR-2026-0412",
      date_execution: dans(1).slice(0, 10),
    },
    demandeur_type: "utilisateur",
    demandeur_id: SOFIA,
    statut: "en_attente",
    approbations_requises: 2,
    roles_autorises: ["gerant", "admin", "valideur"],
    regle_id: "00000000-0000-4000-8000-0000000000f2",
    echeance: ilYa(1, 18),
    cree_le: ilYa(3, 11),
    decide_le: null,
    equipe_id: null,
    politique_id: null,
    exige_commentaire: true,
    exige_piece: false,
    exige_motif: true,
  },
  {
    id: id(2),
    client_id: C,
    entite_id: SIEGE,
    module: "filed",
    type_action: "payer_facture",
    objet_type: "filed_facture",
    objet_id: "R2026-000014",
    resume: "Payer la facture R2026-000014 — Papeterie Durand, 486,20 €",
    montant: 486.2,
    devise: "EUR",
    payload: { fournisseur: "Papeterie Durand", echeance_facture: dans(6).slice(0, 10), controles: "9 passés, 0 anomalie" },
    demandeur_type: "systeme",
    demandeur_id: null,
    statut: "en_attente",
    approbations_requises: 1,
    roles_autorises: ["gerant", "admin", "valideur"],
    regle_id: "00000000-0000-4000-8000-0000000000f1",
    echeance: dans(0, 18),
    cree_le: ilYa(1, 8),
    decide_le: null,
    equipe_id: null,
    politique_id: null,
    exige_commentaire: false,
    exige_piece: false,
    exige_motif: true,
  },
  {
    id: id(3),
    client_id: C,
    entite_id: AGENCE,
    module: "rh",
    type_action: "conge",
    objet_type: "conge",
    objet_id: "CG-2026-0318",
    resume: "Congés de Sofia Carvalho du 13 au 17 octobre (5 jours)",
    montant: null,
    devise: "EUR",
    payload: { du: "2026-10-13", au: "2026-10-17", solde_restant: "17,5 jours", remplacement: "Yanis Dupré" },
    demandeur_type: "utilisateur",
    demandeur_id: SOFIA,
    statut: "en_attente",
    approbations_requises: 1,
    roles_autorises: ["gerant", "admin"],
    regle_id: "00000000-0000-4000-8000-0000000000f4",
    echeance: dans(3, 12),
    cree_le: ilYa(2, 16),
    decide_le: null,
    equipe_id: null,
    politique_id: null,
    exige_commentaire: false,
    exige_piece: false,
    exige_motif: true,
  },
  {
    id: id(4),
    client_id: C,
    entite_id: SIEGE,
    module: "achats",
    type_action: "commande",
    objet_type: "filed_commande",
    objet_id: "BC-2026-0077",
    resume: "Commande de 12 postes de travail — TechPro Informatique, 8 940,00 €",
    montant: 8940,
    devise: "EUR",
    payload: { fournisseur: "TechPro Informatique", lignes: 3, livraison: dans(14).slice(0, 10) },
    demandeur_type: "utilisateur",
    demandeur_id: EXEMPLE_MOI,
    statut: "en_attente",
    approbations_requises: 1,
    roles_autorises: ["gerant", "admin", "valideur"],
    regle_id: "00000000-0000-4000-8000-0000000000f3",
    echeance: dans(2, 18),
    cree_le: ilYa(0, 8),
    decide_le: null,
    equipe_id: null,
    politique_id: null,
    exige_commentaire: false,
    exige_piece: true,
    exige_motif: true,
  },
  {
    id: id(5),
    client_id: C,
    entite_id: SIEGE,
    module: "tresorerie",
    type_action: "decouvert",
    objet_type: "compte_bancaire",
    objet_id: "FR76-…-9143",
    resume: "Autorisation de découvert temporaire — 25 000,00 € jusqu'au 31 octobre",
    montant: 25000,
    devise: "EUR",
    payload: { banque: "Crédit Lyonnais", jusqu_au: "2026-10-31", motif: "Décalage d'encaissement chantier Confluence", exigences: { commentaire: true, piece_jointe: true, motif_refus: true } },
    demandeur_type: "utilisateur",
    demandeur_id: MARC,
    statut: "en_attente",
    approbations_requises: 3,
    roles_autorises: ["gerant", "admin"],
    regle_id: "00000000-0000-4000-8000-0000000000f5",
    echeance: dans(1, 12),
    cree_le: ilYa(1, 14),
    decide_le: null,
    equipe_id: null,
    politique_id: null,
    exige_commentaire: true,
    exige_piece: true,
    exige_motif: true,
  },
  {
    id: id(6),
    client_id: C,
    entite_id: SIEGE,
    module: "filed",
    type_action: "lever_anomalie",
    objet_type: "filed_facture",
    objet_id: "R2026-000009",
    resume: "Lever le contrôle IBAN sur R2026-000009 — nouvel IBAN proposé par Métallerie Roux",
    montant: 12480,
    devise: "EUR",
    payload: { controle: "fournisseur.iban_connu", ancien_iban: "FR76 1027 8060 0100 0203 0450 183", nouvel_iban: "FR76 3000 4000 0512 3456 7890 143", exigences: { commentaire: true, piece_jointe: true, motif_refus: true } },
    demandeur_type: "utilisateur",
    demandeur_id: SOFIA,
    statut: "en_attente",
    approbations_requises: 2,
    roles_autorises: ["gerant", "admin"],
    regle_id: "00000000-0000-4000-8000-0000000000f6",
    echeance: dans(5, 18),
    cree_le: ilYa(0, 10),
    decide_le: null,
    equipe_id: null,
    politique_id: null,
    exige_commentaire: true,
    exige_piece: true,
    exige_motif: true,
  },
  {
    id: id(7),
    client_id: C,
    entite_id: AGENCE,
    module: "loc",
    type_action: "remboursement_caution",
    objet_type: "loc_contrat",
    objet_id: "LC-2026-118",
    resume: "Rembourser la caution du contrat LC-2026-118 — 1 200,00 €",
    montant: 1200,
    devise: "EUR",
    payload: { locataire: "SCI Les Tilleuls", etat_des_lieux: "sans réserve", restitution: ilYa(2).slice(0, 10) },
    demandeur_type: "utilisateur",
    demandeur_id: YANIS,
    statut: "en_attente",
    approbations_requises: 1,
    roles_autorises: ["gerant", "admin", "valideur"],
    regle_id: "00000000-0000-4000-8000-0000000000f1",
    echeance: dans(8, 18),
    cree_le: ilYa(1, 9),
    decide_le: null,
    equipe_id: null,
    politique_id: null,
    exige_commentaire: false,
    exige_piece: false,
    exige_motif: true,
  },
  {
    id: id(8),
    client_id: C,
    entite_id: SIEGE,
    module: "cashd",
    type_action: "prelevement_sepa",
    objet_type: "mandat_sepa",
    objet_id: "EDL-00421",
    resume: "Prélèvement SEPA Électricité de Lyon — 2 316,70 €, échéance du 20",
    montant: 2316.7,
    devise: "EUR",
    payload: { creancier: "Électricité de Lyon", mandat: "EDL-00421", periode: "septembre 2026" },
    demandeur_type: "systeme",
    demandeur_id: null,
    statut: "en_attente",
    approbations_requises: 1,
    roles_autorises: ["gerant", "admin", "valideur"],
    regle_id: "00000000-0000-4000-8000-0000000000f1",
    echeance: null,
    cree_le: ilYa(0, 6),
    decide_le: null,
    equipe_id: null,
    politique_id: null,
    exige_commentaire: false,
    exige_piece: false,
    exige_motif: true,
  },
  /* ——— déjà décidées, pour l'historique ——— */
  {
    id: id(9),
    client_id: C,
    entite_id: SIEGE,
    module: "cashd",
    type_action: "virement_fournisseur",
    objet_type: "filed_facture",
    objet_id: "R2026-000008",
    resume: "Virement à Électricité de Lyon — facture 2026-08, 2 298,40 €",
    montant: 2298.4,
    devise: "EUR",
    payload: {},
    demandeur_type: "systeme",
    demandeur_id: null,
    statut: "executee",
    approbations_requises: 1,
    roles_autorises: ["gerant", "admin", "valideur"],
    regle_id: "00000000-0000-4000-8000-0000000000f1",
    echeance: ilYa(6, 18),
    cree_le: ilYa(8, 8),
    decide_le: ilYa(7, 10),
    equipe_id: null,
    politique_id: null,
    exige_commentaire: false,
    exige_piece: false,
    exige_motif: true,
  },
  {
    id: id(10),
    client_id: C,
    entite_id: AGENCE,
    module: "achats",
    type_action: "commande",
    objet_type: "filed_commande",
    objet_id: "BC-2026-0071",
    resume: "Commande d'outillage — Würth, 3 120,00 €",
    montant: 3120,
    devise: "EUR",
    payload: {},
    demandeur_type: "utilisateur",
    demandeur_id: YANIS,
    statut: "rejetee",
    approbations_requises: 1,
    roles_autorises: ["gerant", "admin", "valideur"],
    regle_id: "00000000-0000-4000-8000-0000000000f3",
    echeance: ilYa(4, 18),
    cree_le: ilYa(6, 8),
    decide_le: ilYa(5, 15),
    equipe_id: null,
    politique_id: null,
    exige_commentaire: false,
    exige_piece: false,
    exige_motif: true,
  },
  {
    id: id(11),
    client_id: C,
    entite_id: SIEGE,
    module: "rh",
    type_action: "conge",
    objet_type: "conge",
    objet_id: "CG-2026-0311",
    resume: "Congés de Yanis Dupré du 2 au 3 octobre (2 jours)",
    montant: null,
    devise: "EUR",
    payload: {},
    demandeur_type: "utilisateur",
    demandeur_id: YANIS,
    statut: "approuvee",
    approbations_requises: 1,
    roles_autorises: ["gerant", "admin"],
    regle_id: "00000000-0000-4000-8000-0000000000f4",
    echeance: ilYa(9, 18),
    cree_le: ilYa(12, 8),
    decide_le: ilYa(11, 9),
    equipe_id: null,
    politique_id: null,
    exige_commentaire: false,
    exige_piece: false,
    exige_motif: true,
  },
];

export const APPROBATIONS_EXEMPLE: Approbation[] = [
  {
    id: "00000000-0000-4000-8000-0000000000b1",
    demande_id: id(1),
    client_id: C,
    user_id: YANIS,
    au_nom_de: null,
    delegation_id: null,
    piece_id: null,
    decision: "approuve",
    commentaire: "Facture rapprochée du bon de commande BC-2026-0064, montants identiques.",
    decide_le: ilYa(2, 15),
  },
  {
    id: "00000000-0000-4000-8000-0000000000b2",
    demande_id: id(5),
    client_id: C,
    user_id: CLAIRE,
    au_nom_de: null,
    delegation_id: null,
    piece_id: null,
    decision: "approuve",
    commentaire: "Vu avec la banque ce matin : accord de principe, taux inchangé.",
    decide_le: ilYa(0, 11),
  },
  {
    id: "00000000-0000-4000-8000-0000000000b3",
    demande_id: id(9),
    client_id: C,
    user_id: EXEMPLE_MOI,
    au_nom_de: null,
    delegation_id: null,
    piece_id: null,
    decision: "approuve",
    commentaire: null,
    decide_le: ilYa(7, 10),
  },
  {
    id: "00000000-0000-4000-8000-0000000000b4",
    demande_id: id(10),
    client_id: C,
    user_id: CLAIRE,
    au_nom_de: null,
    delegation_id: null,
    piece_id: null,
    decision: "rejete",
    commentaire: "Hors budget du trimestre — à représenter en janvier avec le devis Facom en comparaison.",
    decide_le: ilYa(5, 15),
  },
  {
    id: "00000000-0000-4000-8000-0000000000b5",
    demande_id: id(11),
    client_id: C,
    user_id: EXEMPLE_MOI,
    au_nom_de: CLAIRE,
    delegation_id: "00000000-0000-4000-8000-0000000000c1",
    piece_id: null,
    decision: "approuve",
    commentaire: "Au nom de Claire Morel (délégation du mois).",
    decide_le: ilYa(11, 9),
  },
];

export const DELEGATIONS_EXEMPLE: Delegation[] = [
  {
    id: "00000000-0000-4000-8000-0000000000c1",
    client_id: C,
    delegant: CLAIRE,
    delegataire: EXEMPLE_MOI,
    entite_id: null,
    module: null,
    debut: ilYa(14),
    fin: dans(16),
    motif: "Déplacement sur le chantier de Confluence, puis congés.",
    revoquee_le: null,
  },
];

export const REGLES_EXEMPLE: Regle[] = [
  { id: "00000000-0000-4000-8000-0000000000f1", entite_id: null, module: "*", type_action: null, montant_min: 0, montant_max: 5000, approbations_requises: 1, roles_autorises: ["gerant", "admin", "valideur"], actif: true, equipe_id: null, exige_commentaire: false, exige_piece: false, exige_motif: true },
  { id: "00000000-0000-4000-8000-0000000000f2", entite_id: null, module: "cashd", type_action: "virement_fournisseur", montant_min: 5000, montant_max: 20000, approbations_requises: 2, roles_autorises: ["gerant", "admin", "valideur"], actif: true, equipe_id: null, exige_commentaire: true, exige_piece: false, exige_motif: true },
  { id: "00000000-0000-4000-8000-0000000000f3", entite_id: null, module: "achats", type_action: "commande", montant_min: 2000, montant_max: null, approbations_requises: 1, roles_autorises: ["gerant", "admin", "valideur"], actif: true, equipe_id: null, exige_commentaire: false, exige_piece: true, exige_motif: true },
  { id: "00000000-0000-4000-8000-0000000000f4", entite_id: null, module: "rh", type_action: "conge", montant_min: 0, montant_max: null, approbations_requises: 1, roles_autorises: ["gerant", "admin"], actif: true, equipe_id: null, exige_commentaire: false, exige_piece: false, exige_motif: true },
  { id: "00000000-0000-4000-8000-0000000000f5", entite_id: null, module: "tresorerie", type_action: null, montant_min: 20000, montant_max: null, approbations_requises: 3, roles_autorises: ["gerant", "admin"], actif: true, equipe_id: null, exige_commentaire: true, exige_piece: true, exige_motif: true },
  { id: "00000000-0000-4000-8000-0000000000f6", entite_id: null, module: "filed", type_action: "lever_anomalie", montant_min: 0, montant_max: null, approbations_requises: 2, roles_autorises: ["gerant", "admin"], actif: true, equipe_id: null, exige_commentaire: true, exige_piece: true, exige_motif: true },
];
